export interface Skill {
  id: string;
  title: string;
  category: string;
  description: string;
  keyPoints: string[];
  formulas: string[];
  specifications: Record<string, string>;
  applications: string[];
  relatedSkills: string[];
  complexity: number;
  source: string;
}

export interface KnowledgeBase {
  metadata: {
    version: string;
    totalSkills: number;
    categories: string[];
    createdAt: string;
  };
  skills: Skill[];
}

export const knowledgeBase: KnowledgeBase = {
  "metadata": {
    "version": "1.0",
    "totalSkills": 20,
    "categories": ["Physics", "Materials", "Mechanics", "Circuits", "Aerodynamics", "Control_Systems"],
    "createdAt": "2026-01-15"
  },
  "skills": [
    {
      "id": "skill_001",
      "title": "Lift Force Calculation",
      "category": "Physics",
      "description": "Lift is the aerodynamic force generated perpendicular to airflow direction, proportional to air density, velocity squared, and blade area. Critical for calculating drone thrust requirements and load capacity. Understanding lift enables engineers to size rotors and determine maximum takeoff weight.",
      "keyPoints": [
        "Lift force increases with square of velocity (doubling speed = 4x lift)",
        "Proportional to rotor disk area and blade shape (airfoil profile)",
        "Depends on air density which decreases at higher altitudes (~12% less at 1000m)",
        "Generated by pressure difference across blade surfaces (Bernoulli's principle)",
        "Must exceed weight of drone + payload for sustained hover and climb"
      ],
      "formulas": [
        "L = 0.5 × ρ × v² × A × C_L",
        "Where: ρ = air density (kg/m³), v = airflow velocity (m/s), A = blade planform area (m²), C_L = lift coefficient (dimensionless)",
        "Thrust (hover) = m × g, where m = total mass (kg), g = 9.81 m/s²"
      ],
      "specifications": {
        "air_density_sea_level": "1.225 kg/m³",
        "air_density_1000m": "1.112 kg/m³",
        "air_density_3000m": "0.909 kg/m³",
        "standard_gravity": "9.81 m/s²",
        "typical_CL_range": "0.8–1.2 for rotor blades",
        "max_CL_before_stall": "1.4–1.6 depending on airfoil"
      },
      "applications": [
        "Calculate minimum RPM for hovering at a given altitude",
        "Determine maximum payload capacity for delivery drones",
        "Design rotor blade diameter for specific thrust-to-weight ratio",
        "Stability and performance analysis during aggressive maneuvers"
      ],
      "relatedSkills": ["skill_002", "skill_009", "skill_015"],
      "complexity": 7,
      "source": "Fundamentals of Aerodynamics (Anderson, 6th Ed.), NACA Technical Reports"
    },
    {
      "id": "skill_002",
      "title": "Drag Force Analysis",
      "category": "Physics",
      "description": "Drag is the aerodynamic resistance force acting opposite to the direction of motion through a fluid (air). It directly impacts a drone's maximum speed, energy consumption, and flight endurance. Drag consists of parasitic drag (form + skin friction) and induced drag (byproduct of lift).",
      "keyPoints": [
        "Drag increases with the square of velocity, making high-speed flight exponentially costly",
        "Parasitic drag depends on frontal area and surface smoothness of the airframe",
        "Induced drag is inversely proportional to aspect ratio of rotor/wing",
        "Total drag = Parasitic drag + Induced drag at any given airspeed",
        "Minimizing drag coefficient (C_D) is key to extending flight time and range"
      ],
      "formulas": [
        "D = 0.5 × ρ × v² × A × C_D",
        "Where: D = drag force (N), ρ = air density (kg/m³), v = velocity (m/s), A = reference area (m²), C_D = drag coefficient",
        "Induced Drag: D_i = L² / (0.5 × ρ × v² × π × b² × e), where b = wingspan/rotor span, e = Oswald efficiency (0.7–0.9)"
      ],
      "specifications": {
        "CD_flat_plate": "1.28 (perpendicular to flow)",
        "CD_streamlined_body": "0.04–0.10",
        "CD_sphere": "0.47",
        "CD_typical_drone_frame": "0.25–0.45",
        "reynolds_number_threshold": "500,000 for turbulent transition"
      },
      "applications": [
        "Estimate battery drain at various cruise speeds for mission planning",
        "Optimize airframe shape for reduced drag in racing drones",
        "Calculate wind resistance for outdoor industrial inspection drones",
        "Determine terminal velocity and safe descent rates"
      ],
      "relatedSkills": ["skill_001", "skill_017", "skill_003"],
      "complexity": 7,
      "source": "Introduction to Flight (Anderson, 8th Ed.), NASA TM-2003-212030"
    },
    {
      "id": "skill_003",
      "title": "Newton's Laws Applied to Drones",
      "category": "Physics",
      "description": "Newton's three laws of motion form the foundation of drone flight dynamics. The first law governs inertia during hover, the second law (F=ma) determines acceleration from net forces, and the third law explains thrust generation as reaction to accelerating air downward.",
      "keyPoints": [
        "First Law: A drone in hover remains in hover unless net force is applied (equilibrium)",
        "Second Law: F = m × a governs all translational and rotational accelerations",
        "Third Law: Rotors push air down, air pushes drone up (action-reaction thrust)",
        "Net force = Thrust – Weight – Drag for vertical/horizontal analysis",
        "Rotational analogs: Torque = I × α where I is moment of inertia, α is angular acceleration"
      ],
      "formulas": [
        "F_net = m × a (Newton's Second Law)",
        "W = m × g (Weight force, where g = 9.81 m/s²)",
        "Thrust required for hover: T = W = m × g",
        "Climb acceleration: a = (T − W − D) / m",
        "Torque: τ = I × α, where I = moment of inertia (kg·m²), α = angular acceleration (rad/s²)"
      ],
      "specifications": {
        "gravitational_acceleration": "9.81 m/s² (sea level)",
        "typical_drone_mass_range": "0.25 – 25 kg",
        "thrust_to_weight_ratio_hover": "1.0 (minimum)",
        "thrust_to_weight_ratio_acrobatic": "2.0 – 4.0",
        "typical_max_acceleration": "5 – 15 m/s² for consumer drones"
      },
      "applications": [
        "Calculate thrust needed for vertical takeoff with specific payload",
        "Determine acceleration profiles for autonomous waypoint navigation",
        "Analyze forces during wind gust disturbance rejection",
        "Design motor/propeller combinations for desired performance envelope"
      ],
      "relatedSkills": ["skill_001", "skill_004", "skill_010"],
      "complexity": 5,
      "source": "Engineering Mechanics: Dynamics (Meriam & Kraige, 9th Ed.)"
    },
    {
      "id": "skill_004",
      "title": "Energy & Power Calculations",
      "category": "Physics",
      "description": "Energy and power calculations determine how long a drone can fly, how much work its motors can perform, and how to size battery packs. Power is the rate of energy consumption, and understanding the relationship between electrical power input and mechanical power output is essential for flight endurance estimation.",
      "keyPoints": [
        "Electrical power: P = V × I (Voltage × Current in watts)",
        "Mechanical power output of motor = Torque × Angular velocity",
        "Flight endurance = Battery energy (Wh) / Average power consumption (W)",
        "Hover power is typically 60–80% of maximum rated power for efficient designs",
        "Power-to-weight ratio determines climb rate and agility capability"
      ],
      "formulas": [
        "P_electrical = V × I (watts)",
        "P_mechanical = τ × ω, where τ = torque (N·m), ω = angular velocity (rad/s)",
        "Energy = P × t, where t = time (seconds or hours)",
        "Flight time (min) = (Battery capacity in Wh / Power draw in W) × 60",
        "Efficiency: η = P_mechanical / P_electrical × 100%"
      ],
      "specifications": {
        "typical_motor_efficiency": "80–90% for quality BLDC motors",
        "ESC_efficiency": "95–99%",
        "propeller_efficiency": "50–80% depending on design",
        "overall_system_efficiency": "40–65%",
        "hover_power_5kg_drone": "150–300 W typical",
        "energy_density_LiPo": "150–260 Wh/kg"
      },
      "applications": [
        "Size battery pack for required 30-minute survey mission",
        "Calculate motor power ratings for heavy-lift agricultural drones",
        "Optimize propeller pitch for maximum efficiency at cruise speed",
        "Thermal management design based on power dissipation estimates"
      ],
      "relatedSkills": ["skill_003", "skill_007", "skill_010"],
      "complexity": 6,
      "source": "Electric Machinery Fundamentals (Chapman, 6th Ed.), Battery University"
    },
    {
      "id": "skill_005",
      "title": "Carbon Fiber Composite Properties",
      "category": "Materials",
      "description": "Carbon fiber reinforced polymer (CFRP) is the premier structural material for high-performance drone frames due to its exceptional strength-to-weight ratio. It consists of carbon filaments embedded in an epoxy resin matrix, offering anisotropic properties that can be tailored through layup orientation.",
      "keyPoints": [
        "Tensile strength 3–7 GPa, approximately 5× stronger than steel per unit weight",
        "Density of 1.55–1.60 g/cm³ compared to aluminum at 2.70 g/cm³ (42% lighter)",
        "Anisotropic: strength depends on fiber orientation in the layup",
        "Brittle failure mode — no plastic deformation warning before fracture",
        "Excellent fatigue resistance but vulnerable to impact damage (delamination)"
      ],
      "formulas": [
        "Specific strength = Tensile strength / Density",
        "CFRP specific strength ≈ 2,457 kN·m/kg vs Steel ≈ 254 kN·m/kg",
        "Rule of Mixtures: E_composite = V_f × E_f + V_m × E_m",
        "Where: V_f = fiber volume fraction, E_f = fiber modulus, V_m = matrix volume fraction, E_m = matrix modulus"
      ],
      "specifications": {
        "tensile_strength": "3,500–7,000 MPa (depending on grade)",
        "elastic_modulus": "230–400 GPa (standard to high modulus)",
        "density": "1.55–1.60 g/cm³",
        "elongation_at_break": "1.5–2.0%",
        "thermal_conductivity": "6–10 W/(m·K) axial",
        "cost_per_kg": "$15–$150 (standard to aerospace grade)",
        "fiber_diameter": "5–10 μm per filament"
      },
      "applications": [
        "Racing drone frames achieving sub-200g total weight with high rigidity",
        "Propeller blades for vibration-free, high-RPM operation",
        "Boom arms for large industrial drones requiring stiffness and light weight",
        "UAV wing spars for fixed-wing long-endurance platforms"
      ],
      "relatedSkills": ["skill_006", "skill_008", "skill_011"],
      "complexity": 6,
      "source": "ASM Handbook Vol. 21: Composites, ASTM D3039 (Tensile Testing of Composites)"
    },
    {
      "id": "skill_006",
      "title": "Aluminum Alloy Specifications",
      "category": "Materials",
      "description": "Aluminum alloys, particularly 6061-T6 and 7075-T6, are widely used in drone components such as motor mounts, landing gear, and CNC-machined parts. They offer excellent machinability, corrosion resistance, and a good balance between strength, weight, and cost compared to steel or titanium.",
      "keyPoints": [
        "6061-T6 offers good weldability and corrosion resistance for general structural use",
        "7075-T6 has 40% higher strength than 6061-T6 but poorer weldability and corrosion resistance",
        "T6 temper indicates solution heat treated and artificially aged for peak strength",
        "Density is approximately one-third of steel (2.70 vs 7.85 g/cm³)",
        "Excellent thermal conductivity makes it suitable for motor mounts acting as heat sinks"
      ],
      "formulas": [
        "Yield safety factor: SF = σ_yield / σ_applied",
        "Stress: σ = F / A (Force / Cross-sectional area in Pa)",
        "Thermal expansion: ΔL = α × L₀ × ΔT",
        "Where: α = coefficient of thermal expansion (23.6 × 10⁻⁶ /°C for 6061), L₀ = original length, ΔT = temperature change"
      ],
      "specifications": {
        "6061_T6_yield_strength": "276 MPa",
        "6061_T6_ultimate_tensile": "310 MPa",
        "7075_T6_yield_strength": "503 MPa",
        "7075_T6_ultimate_tensile": "572 MPa",
        "density_aluminum": "2.70 g/cm³",
        "elastic_modulus": "68.9 GPa (6061), 71.7 GPa (7075)",
        "thermal_conductivity": "167 W/(m·K) for 6061-T6",
        "cost_per_kg_6061": "$3–$8",
        "cost_per_kg_7075": "$6–$15"
      },
      "applications": [
        "CNC-machined motor mounts with integrated heat dissipation for heavy-lift drones",
        "Landing gear struts requiring impact resistance and repairability",
        "Gimbal frames for camera stabilization systems requiring tight tolerances",
        "Structural connectors and brackets in modular drone frame assemblies"
      ],
      "relatedSkills": ["skill_005", "skill_012", "skill_011"],
      "complexity": 5,
      "source": "ASM Handbook Vol. 2: Aluminum & Aluminum Alloys, ASTM B209, MIL-HDBK-5J"
    },
    {
      "id": "skill_007",
      "title": "Lithium Polymer Battery Specs",
      "category": "Materials",
      "description": "Lithium Polymer (LiPo) batteries are the dominant power source for multirotor drones due to their high energy density, high discharge capability, and lightweight packaging. Understanding cell voltage, capacity (mAh), C-rating, and series/parallel configurations is critical for safe and optimal drone power system design.",
      "keyPoints": [
        "Nominal cell voltage is 3.7V (fully charged 4.2V, storage 3.85V, cutoff 3.3V)",
        "Energy density of 150–260 Wh/kg, significantly higher than NiMH (60–120 Wh/kg)",
        "C-rating defines maximum continuous discharge: Current(A) = C-rate × Capacity(Ah)",
        "Series (S) configurations increase voltage; parallel (P) increases capacity",
        "Thermal runaway risk above 60°C — requires proper BMS and physical protection"
      ],
      "formulas": [
        "Pack voltage = Cells in series × 3.7V (nominal)",
        "Max continuous current = C-rating × Capacity (Ah)",
        "Energy (Wh) = Voltage (V) × Capacity (Ah)",
        "Flight time ≈ (Capacity in mAh × 60) / (Average current draw in mA) minutes",
        "Example: 6S (22.2V) × 5000mAh = 111 Wh pack energy"
      ],
      "specifications": {
        "nominal_cell_voltage": "3.7V",
        "full_charge_voltage": "4.20V per cell",
        "low_voltage_cutoff": "3.3V per cell (recommended)",
        "energy_density": "150–260 Wh/kg",
        "typical_C_rating": "25C–100C for drone packs",
        "cycle_life": "200–500 cycles to 80% capacity",
        "common_configs": "3S, 4S, 6S (11.1V, 14.8V, 22.2V)",
        "weight_example_6S_5000mAh": "680–800g"
      },
      "applications": [
        "Size battery packs for 25+ minute flight endurance on survey drones",
        "Calculate maximum current draw for motor/ESC compatibility",
        "Design redundant power systems for safety-critical inspection UAVs",
        "Weight budget optimization — battery is typically 25–40% of total drone mass"
      ],
      "relatedSkills": ["skill_004", "skill_014", "skill_013"],
      "complexity": 5,
      "source": "Battery University, IEC 62133 (Safety of Portable Cells), Electrochem. Soc. Journal"
    },
    {
      "id": "skill_008",
      "title": "Composite Material Engineering",
      "category": "Materials",
      "description": "Composite materials combine two or more constituent materials (fibers + matrix) to achieve superior properties not attainable by either alone. In drone engineering, glass fiber, Kevlar (aramid), and hybrid composites complement carbon fiber for applications requiring impact resistance, flexibility, or cost efficiency.",
      "keyPoints": [
        "Glass fiber (E-glass) offers good strength at 1/10th the cost of carbon fiber",
        "Kevlar/Aramid provides exceptional impact and abrasion resistance (used in propeller guards)",
        "Hybrid layups (carbon + Kevlar) combine stiffness with impact damage tolerance",
        "Fiber volume fraction (Vf) typically 50–65% for optimal mechanical properties",
        "Manufacturing methods: hand layup, vacuum bagging, autoclave, filament winding"
      ],
      "formulas": [
        "Rule of Mixtures (longitudinal): E₁ = V_f × E_f + (1 − V_f) × E_m",
        "Transverse modulus: 1/E₂ = V_f/E_f + (1 − V_f)/E_m",
        "Composite density: ρ_c = V_f × ρ_f + (1 − V_f) × ρ_m",
        "Specific stiffness = E / ρ (used to compare materials on a weight basis)"
      ],
      "specifications": {
        "E_glass_tensile_strength": "2,000–3,500 MPa",
        "E_glass_density": "2.54 g/cm³",
        "E_glass_elastic_modulus": "72–85 GPa",
        "kevlar_49_tensile_strength": "3,000–3,600 MPa",
        "kevlar_49_density": "1.44 g/cm³",
        "kevlar_49_elastic_modulus": "112–124 GPa",
        "glass_fiber_cost": "$1–$5 per kg",
        "kevlar_cost": "$20–$40 per kg"
      },
      "applications": [
        "Propeller guards using Kevlar-reinforced nylon for crash survivability",
        "Glass fiber drone canopies balancing cost, weight, and RF transparency for GPS/radio",
        "Hybrid carbon/Kevlar fuselage panels for military reconnaissance UAVs",
        "Filament-wound motor booms for high torsional stiffness at minimal weight"
      ],
      "relatedSkills": ["skill_005", "skill_006", "skill_011"],
      "complexity": 7,
      "source": "Principles of Composite Material Mechanics (Gibson, 4th Ed.), ASTM D3518, MIL-HDBK-17"
    },
    {
      "id": "skill_009",
      "title": "Rotor Blade Design Principles",
      "category": "Mechanics",
      "description": "Rotor blade design encompasses pitch angle, chord length, blade count, diameter, and airfoil selection to optimize thrust generation and efficiency. The propeller is the interface between electrical power and aerodynamic thrust, making its design the single most impactful factor in drone performance.",
      "keyPoints": [
        "Pitch is the theoretical distance a propeller advances per revolution (measured in inches)",
        "Higher pitch = more speed but less thrust at low RPM; lower pitch = more static thrust",
        "Blade diameter determines disk area and directly affects maximum available thrust",
        "Propeller notation: Diameter × Pitch (e.g., 10×4.5 means 10\" diameter, 4.5\" pitch)",
        "Increasing blade count (2→3) increases thrust ~15–25% but reduces peak efficiency"
      ],
      "formulas": [
        "Disk area: A = π × (D/2)², where D = propeller diameter",
        "Tip speed: v_tip = π × D × (RPM / 60)",
        "Advance ratio: J = v / (n × D), where v = forward speed, n = rev/sec",
        "Thrust coefficient: C_T = T / (ρ × n² × D⁴)",
        "Static thrust ∝ D³·⁵ (approximate empirical scaling for similar designs)"
      ],
      "specifications": {
        "common_diameters_mini_quad": "5–7 inches (127–178 mm)",
        "common_diameters_photography": "9–15 inches (229–381 mm)",
        "common_diameters_heavy_lift": "15–30 inches (381–762 mm)",
        "typical_pitch_range": "3.0–6.0 inches",
        "max_tip_speed_guideline": "< 0.7 Mach (< 238 m/s) to avoid compressibility",
        "blade_materials": "Nylon, carbon-nylon, full carbon fiber, wood"
      },
      "applications": [
        "Select optimal prop size for 5\" FPV racing quad maximizing thrust-to-weight",
        "Design folding propellers for portable mapping drones with diameter constraints",
        "Calculate required RPM range for a heavy-lift hexacopter carrying 5kg payload",
        "Noise reduction through blade tip design and lower tip-speed operation"
      ],
      "relatedSkills": ["skill_001", "skill_010", "skill_015"],
      "complexity": 8,
      "source": "Rotor Aerodynamics (Leishman), APC Propeller Performance Database, UIUC Airfoil Database"
    },
    {
      "id": "skill_010",
      "title": "BLDC Motor Torque & Efficiency",
      "category": "Mechanics",
      "description": "Brushless DC (BLDC) motors convert electrical energy to rotational mechanical energy and are the universal choice for multirotor drones. Key parameters include KV rating (RPM per volt), torque constant, efficiency curves, and thermal limits. Motor selection must match propeller characteristics for optimal system efficiency.",
      "keyPoints": [
        "KV rating = unloaded RPM per volt (e.g., 920KV motor on 22.2V ≈ 20,424 RPM no-load)",
        "Low KV motors (< 400) suit large props; high KV (> 2000) suit small, high-speed props",
        "Torque constant Kt = 1 / (KV × 2π/60) in N·m/A — inversely proportional to KV",
        "Peak efficiency (80–92%) occurs at ~70–80% of maximum rated load",
        "Motor heat is primary failure mode — max winding temperature typically 180°C"
      ],
      "formulas": [
        "No-load RPM = KV × Voltage",
        "Torque constant: K_t = 60 / (2π × KV) in N·m/A",
        "Mechanical power: P_mech = τ × ω = K_t × I × 2π × RPM/60",
        "Electrical power: P_elec = V × I",
        "Motor efficiency: η = P_mech / P_elec × 100%",
        "Thermal: ΔT = P_loss × R_thermal (°C per watt dissipated)"
      ],
      "specifications": {
        "typical_KV_range_multirotors": "300–2800 KV",
        "common_sizes_format": "XXYY (stator diameter mm × stator height mm)",
        "example_2207_motor_weight": "28–34g",
        "example_2207_max_thrust": "1200–1800g on 5\" prop",
        "peak_efficiency_range": "80–92%",
        "idle_current_draw": "0.3–1.5A (no-load)",
        "max_continuous_current_typical": "25–40A for 5\" motors"
      },
      "applications": [
        "Match motor KV to propeller pitch and battery voltage for target RPM range",
        "Thermal analysis to determine maximum hover duration without overheating",
        "Calculate thrust tables across throttle range for flight controller tuning",
        "Motor redundancy analysis for hexacopter/octocopter failure modes"
      ],
      "relatedSkills": ["skill_004", "skill_009", "skill_013"],
      "complexity": 7,
      "source": "Electric Motors & Drives (Hughes & Drury, 5th Ed.), T-Motor & BrotherHobby Datasheets"
    },
    {
      "id": "skill_011",
      "title": "Frame Structural Design",
      "category": "Mechanics",
      "description": "Frame structural design involves material selection, topology, load path analysis, and vibration management to create a drone airframe that is stiff, lightweight, and durable. The frame must withstand flight loads, crash impacts, and motor vibrations while keeping total weight minimal.",
      "keyPoints": [
        "Stiffness-to-weight ratio is the primary design metric (not just strength)",
        "Vibration isolation between motors and flight controller is critical for sensor accuracy",
        "Monocoque designs (stressed skin) are lighter than truss-frame for same stiffness",
        "Arm cross-section geometry (tube vs. plate) dramatically affects torsional rigidity",
        "FEA (Finite Element Analysis) is used to optimize geometry and reduce material usage"
      ],
      "formulas": [
        "Bending stress: σ = M × y / I, where M = bending moment, y = distance from neutral axis, I = moment of inertia",
        "Deflection (cantilever beam): δ = F × L³ / (3 × E × I)",
        "Natural frequency: f_n = (1/2π) × √(k/m), where k = stiffness, m = mass",
        "Torsional stiffness: GJ, where G = shear modulus, J = polar moment of inertia",
        "Buckling load (Euler): P_cr = π² × E × I / L² for slender columns"
      ],
      "specifications": {
        "typical_arm_thickness_CF": "3–5 mm (carbon fiber plate)",
        "recommended_safety_factor": "2.0–3.0 for drone frames",
        "vibration_isolation_frequency": "< 30 Hz typical motor vibration range",
        "typical_frame_weight_5inch": "20–35g (carbon fiber)",
        "typical_frame_weight_photography": "200–600g",
        "bolt_torque_M3_CF": "0.3–0.5 N·m (to avoid crushing)"
      },
      "applications": [
        "Topology optimization of a quadcopter center plate to reduce weight by 25%",
        "Vibration dampening mount design for flight controller and GPS module",
        "Crash-survivable arm attachment design using replaceable quick-swap arms",
        "Modal analysis to ensure frame natural frequencies avoid motor RPM excitation"
      ],
      "relatedSkills": ["skill_005", "skill_006", "skill_012"],
      "complexity": 8,
      "source": "Mechanics of Materials (Hibbeler, 10th Ed.), ANSYS FEA Documentation"
    },
    {
      "id": "skill_012",
      "title": "Joint Mechanics & Fasteners",
      "category": "Mechanics",
      "description": "Joint mechanics covers the design and analysis of bolted connections, press fits, adhesive bonds, and threaded fasteners used in drone assemblies. Proper joint design prevents loosening from vibration, distributes stress evenly, and allows for serviceability of modular components.",
      "keyPoints": [
        "Bolt preload is critical — properly torqued bolts resist vibration loosening",
        "Thread-locking compound (Loctite 243) is standard for drone motor mount bolts",
        "Stress concentration factor at bolt holes in CF plates: Kt ≈ 2.5–3.0",
        "Minimum edge distance for bolted joints in composites: 3× bolt diameter",
        "Nyloc (nylon-insert) lock nuts rated for temperatures up to 120°C"
      ],
      "formulas": [
        "Bolt preload: F_i = T / (K × d), where T = torque, K = nut factor (≈0.2), d = bolt diameter",
        "Shear stress in bolt: τ = V / A_s, where V = shear force, A_s = shear area",
        "Bearing stress: σ_b = F / (d × t), where d = bolt diameter, t = plate thickness",
        "Stress concentration: σ_max = K_t × σ_nominal",
        "Joint efficiency: η = (Strength of joint / Strength of base material) × 100%"
      ],
      "specifications": {
        "M3_bolt_tensile_strength_12_9": "1,220 MPa",
        "M3_recommended_torque": "1.0–1.3 N·m (steel in steel)",
        "M3_torque_in_CF": "0.3–0.5 N·m (to prevent crushing)",
        "loctite_243_shear_strength": "7–10 N/mm² on M3",
        "nyloc_nut_prevailing_torque": "0.10–0.25 N·m for M3",
        "minimum_edge_distance_CF": "3D (3 × bolt diameter)"
      },
      "applications": [
        "Motor mounting bolt pattern design for vibration-prone BLDC motors",
        "Quick-release arm attachment mechanisms for field-repairable drones",
        "Adhesive bonding analysis for permanently fixed GPS mast assemblies",
        "Fatigue life estimation of bolted joints under cyclic flight loads"
      ],
      "relatedSkills": ["skill_011", "skill_006", "skill_005"],
      "complexity": 6,
      "source": "Shigley's Mechanical Engineering Design (11th Ed.), VDI 2230 Bolt Calculation Standard"
    },
    {
      "id": "skill_013",
      "title": "ESC Motor Control Systems",
      "category": "Circuits",
      "description": "Electronic Speed Controllers (ESCs) regulate BLDC motor speed by converting DC battery power into three-phase AC at variable frequency. They interpret PWM/DShot signals from the flight controller and use commutation algorithms (FOC or trapezoidal) to precisely control motor RPM and response time.",
      "keyPoints": [
        "PWM signal range: 1000μs (0% throttle) to 2000μs (100% throttle) at 50–500Hz",
        "DShot protocol (digital) eliminates PWM calibration issues — DShot600 is standard",
        "FOC (Field Oriented Control) sinusoidal drive offers smoother, quieter, more efficient operation",
        "ESC current rating must exceed maximum motor draw by 20%+ safety margin",
        "BLHeli_32 and AM32 are common open-source ESC firmware platforms"
      ],
      "formulas": [
        "PWM duty cycle: Throttle % = (Pulse width − 1000) / 1000 × 100",
        "DShot value: 0–2047 (11-bit resolution), with 0 = disarmed, 48–2047 = throttle range",
        "ESC power dissipation: P_loss = I² × R_on × 2 (for two active MOSFETs per phase)",
        "Commutation frequency: f_comm = (RPM / 60) × (Pole pairs)",
        "Recommended ESC rating: I_ESC ≥ 1.2 × I_motor_max"
      ],
      "specifications": {
        "common_ESC_ratings": "20A, 30A, 40A, 60A continuous",
        "PWM_frequency_range": "50–500 Hz (analog), up to 32kHz (motor drive)",
        "DShot600_bit_rate": "600 kbit/s",
        "MOSFET_Rds_on_typical": "1.5–5 mΩ per FET",
        "response_time_DShot": "< 1ms",
        "operating_voltage": "2S–6S (7.4–25.2V), some support 12S (50.4V)"
      },
      "applications": [
        "Configure DShot600 protocol for sub-millisecond throttle response on racing drones",
        "Size ESC current rating for heavy-lift drone with 40A peak per motor",
        "Implement ESC telemetry for real-time RPM, temperature, and current monitoring",
        "Bidirectional DShot for active braking and turtle mode (flip-after-crash)"
      ],
      "relatedSkills": ["skill_010", "skill_014", "skill_019"],
      "complexity": 7,
      "source": "BLHeli_32 Documentation, DShot Protocol Specification, TI DRV8323 Reference Design"
    },
    {
      "id": "skill_014",
      "title": "Battery Management Systems",
      "category": "Circuits",
      "description": "Battery Management Systems (BMS) monitor and protect lithium battery packs by regulating cell voltages, balancing charge distribution, measuring state-of-charge, and preventing dangerous conditions like over-discharge, over-current, and thermal runaway. Critical for both safety and maximizing battery service life.",
      "keyPoints": [
        "Cell balancing ensures all series cells reach 4.20V simultaneously during charging",
        "Over-discharge protection triggers cutoff at 3.0–3.3V per cell to prevent damage",
        "Current sensing via shunt resistor or Hall-effect sensor measures real-time load",
        "State of Charge (SoC) estimation uses voltage mapping + coulomb counting",
        "Temperature monitoring with NTC thermistors; shutdown above 60°C cell temperature"
      ],
      "formulas": [
        "State of Charge: SoC = (Q_remaining / Q_total) × 100%",
        "Coulomb counting: Q = ∫ I(t) dt (integral of current over time)",
        "Cell balance current: I_bal = (V_cell − V_target) / R_balance",
        "Power bus voltage: V_pack = V_cell_min × N_series (worst-case estimate)",
        "Remaining flight time = (SoC × Capacity) / Average_current"
      ],
      "specifications": {
        "balance_charge_current": "100–500 mA per cell typical",
        "over_voltage_protection": "4.25V per cell trigger",
        "under_voltage_protection": "3.0–3.3V per cell trigger",
        "over_current_protection": "varies by application, 50–200A for drone packs",
        "temperature_shutdown": "60–70°C cell surface",
        "SoC_accuracy": "±3–5% for voltage-based, ±1–2% for coulomb counting",
        "balancing_methods": "Passive (resistive) or Active (capacitor/inductor transfer)"
      },
      "applications": [
        "Implement low-voltage RTL (Return-to-Launch) trigger at 3.5V per cell",
        "Design charger with per-cell monitoring for 6S heavy-lift drone battery packs",
        "Real-time SoC telemetry to ground station for mission endurance planning",
        "Post-flight battery health logging to predict replacement intervals"
      ],
      "relatedSkills": ["skill_007", "skill_013", "skill_004"],
      "complexity": 7,
      "source": "IEC 62133-2 (Li-ion Safety), Texas Instruments BQ76940 Technical Reference"
    },
    {
      "id": "skill_015",
      "title": "Sensor Integration & Fusion",
      "category": "Circuits",
      "description": "Modern drones rely on an array of sensors — gyroscopes, accelerometers, magnetometers, barometers, and GPS — fused together to provide accurate attitude, position, and velocity estimates. Sensor fusion algorithms combine noisy, imperfect measurements into a reliable state estimate for the flight controller.",
      "keyPoints": [
        "IMU (Inertial Measurement Unit) combines 3-axis gyro + 3-axis accelerometer minimum",
        "Gyroscope measures angular velocity (°/s) — fast but drifts over time",
        "Accelerometer measures linear acceleration + gravity vector — noisy but no drift",
        "Barometer measures altitude via atmospheric pressure — ±0.5m accuracy typical",
        "Complementary filter or Extended Kalman Filter (EKF) fuses sensor data optimally"
      ],
      "formulas": [
        "Complementary filter: θ = α × (θ + ω_gyro × dt) + (1 − α) × θ_accel",
        "Where: α ≈ 0.98 (high-pass for gyro), dt = sample period",
        "Barometric altitude: h = (T₀/L) × [1 − (P/P₀)^(R×L/(g×M))]",
        "Where: T₀ = 288.15K, L = 0.0065 K/m, P₀ = 101325 Pa, R = 8.31447 J/(mol·K), M = 0.0289644 kg/mol",
        "GPS position accuracy: CEP ≈ 2.5m (civilian), RTK ≈ 0.01–0.02m"
      ],
      "specifications": {
        "gyroscope_range": "±250 to ±2000 °/s (configurable)",
        "accelerometer_range": "±2g to ±16g (configurable)",
        "gyro_noise_density": "0.004–0.01 °/s/√Hz (MEMS)",
        "barometer_resolution": "0.012 hPa (≈0.1m altitude)",
        "IMU_sample_rate": "1–8 kHz (flight controller loop rate)",
        "common_IMU_chips": "BMI270, ICM-42688-P, MPU-6500",
        "magnetometer_resolution": "0.15 μT (e.g., QMC5883L)"
      },
      "applications": [
        "GPS-denied navigation using IMU dead reckoning in indoor warehouse inspection",
        "Altitude hold mode using barometer + accelerometer vertical fusion",
        "Compass-based heading hold for automated survey grid patterns",
        "Vibration analysis from accelerometer data to detect propeller damage"
      ],
      "relatedSkills": ["skill_019", "skill_020", "skill_001"],
      "complexity": 8,
      "source": "Probabilistic Robotics (Thrun, Burgard, Fox), InvenSense ICM-42688-P Datasheet"
    },
    {
      "id": "skill_016",
      "title": "Propeller Aerodynamic Efficiency",
      "category": "Aerodynamics",
      "description": "Propeller efficiency quantifies how effectively a rotor converts shaft mechanical power into useful thrust. It depends on blade geometry (pitch, chord, twist), operating RPM, and flight speed. Optimizing propeller efficiency is the most effective way to extend flight time without adding battery weight.",
      "keyPoints": [
        "Static efficiency (hover) is typically 50–65%; forward flight efficiency can reach 80–85%",
        "Blade Element Momentum Theory (BEMT) models local lift/drag along blade span",
        "Optimal blade twist decreases pitch angle from root to tip to equalize angle of attack",
        "High disk loading (thrust/area) reduces hover efficiency — larger props are more efficient",
        "Ground effect boosts efficiency by ~10–15% when flying within 1 rotor diameter of ground"
      ],
      "formulas": [
        "Propeller efficiency: η_prop = (T × v) / P_shaft (in forward flight)",
        "Hover figure of merit: FM = T^(3/2) / (√(2ρA) × P), ideal FM = 1.0, typical 0.5–0.7",
        "Disk loading: DL = T / A = T / (π × r²) in N/m²",
        "Induced velocity (hover): v_i = √(T / (2ρA))",
        "Power loading: PL = T / P (grams of thrust per watt)"
      ],
      "specifications": {
        "figure_of_merit_small_props": "0.45–0.55 (5–7 inch)",
        "figure_of_merit_large_props": "0.55–0.70 (15+ inch)",
        "disk_loading_mini_quad": "50–150 N/m²",
        "disk_loading_heavy_lift": "20–50 N/m²",
        "power_loading_efficient": "8–12 g/W",
        "power_loading_aggressive": "3–5 g/W",
        "optimal_blade_count_efficiency": "2 blades (highest η, lowest noise)"
      },
      "applications": [
        "Select propeller with highest g/W (power loading) for endurance-focused mapping drone",
        "Design custom twisted blade for heavy-lift agricultural sprayer drone",
        "Compare 2-blade vs 3-blade propellers for noise-critical urban delivery applications",
        "Ground effect analysis for precision landing and low-altitude operations"
      ],
      "relatedSkills": ["skill_009", "skill_001", "skill_004"],
      "complexity": 8,
      "source": "Helicopter Theory (Johnson), UIUC Propeller Data Site, APC Performance Files"
    },
    {
      "id": "skill_017",
      "title": "Flight Stability & CG Analysis",
      "category": "Aerodynamics",
      "description": "Flight stability depends on the relationship between center of gravity (CG), center of thrust, and the moments generated by control inputs. A drone with CG below the center of thrust exhibits pendular stability, while CG offset creates constant corrective control effort, reducing efficiency and flight time.",
      "keyPoints": [
        "CG should be centered laterally and longitudinally within ±5mm of geometric center",
        "CG below thrust plane creates passive pendular stability (self-righting tendency)",
        "CG above thrust plane creates an inverted pendulum — requires active stabilization",
        "Asymmetric mass distribution causes constant motor compensation and uneven battery drain",
        "Moment of inertia around each axis determines rotational responsiveness (agility)"
      ],
      "formulas": [
        "CG position: x_CG = Σ(m_i × x_i) / Σ(m_i) for each axis",
        "Restoring moment: M = m × g × d × sin(θ), where d = CG-to-thrust offset",
        "Moment of inertia: I = Σ(m_i × r_i²)",
        "Angular acceleration from disturbance: α = M_disturbance / I",
        "Tip-over angle: θ_max = arctan(r_base / h_CG), where r_base = landing gear radius"
      ],
      "specifications": {
        "CG_tolerance_racing": "±2 mm from center",
        "CG_tolerance_photography": "±5 mm from center",
        "battery_placement_offset_effect": "1mm offset ≈ 0.5° constant tilt correction",
        "typical_Ixx_5inch_quad": "0.002–0.005 kg·m²",
        "typical_Iyy_5inch_quad": "0.002–0.005 kg·m²",
        "typical_Izz_5inch_quad": "0.003–0.008 kg·m² (yaw axis)"
      },
      "applications": [
        "Battery compartment positioning to center CG on heavy-lift payload drones",
        "Payload release mechanism design that maintains CG throughout mission",
        "Moment of inertia measurement jig for custom frame tuning",
        "Asymmetric arm drone designs (V-tail, Y6) CG compensation calculations"
      ],
      "relatedSkills": ["skill_002", "skill_011", "skill_019"],
      "complexity": 7,
      "source": "Aircraft Stability & Control (Etkin & Reid), ArduPilot CG/Tuning Documentation"
    },
    {
      "id": "skill_018",
      "title": "Wind Resistance & Drag Modeling",
      "category": "Aerodynamics",
      "description": "Wind resistance modeling predicts how external wind loads affect drone flight performance, endurance, and controllability. Understanding drag area coefficients, wind profiles, and gust dynamics is essential for designing drones that operate reliably in outdoor environments with variable weather conditions.",
      "keyPoints": [
        "Drag area (CdA) is the product of drag coefficient and frontal area — key sizing parameter",
        "Wind speed reduces effective ground speed and increases power consumption quadratically",
        "Headwind of v_wind requires additional thrust ≈ 0.5 × ρ × v_wind² × CdA",
        "Turbulent gusts create transient disturbances requiring fast controller response",
        "Wind gradient (shear) near ground level can be modeled as power law profile"
      ],
      "formulas": [
        "Drag force: F_D = 0.5 × ρ × v_wind² × C_D × A_frontal",
        "Power to overcome headwind: P_wind = F_D × v_ground",
        "Wind speed at height h: v(h) = v_ref × (h/h_ref)^α, where α ≈ 0.14 (open terrain)",
        "Gust load factor: n = 1 + (0.5 × ρ × v_gust × a_wing × C_Lα) / (W/S)",
        "Range reduction in headwind: R_actual = R_still × (v_air − v_wind) / v_air"
      ],
      "specifications": {
        "max_operating_wind_consumer": "8–12 m/s (Beaufort 4–5)",
        "max_operating_wind_industrial": "12–18 m/s (Beaufort 6)",
        "CdA_typical_mini_quad": "0.005–0.015 m²",
        "CdA_typical_large_drone": "0.02–0.08 m²",
        "gust_factor_typical": "1.3–1.5 × mean wind speed",
        "air_density_range": "1.00–1.30 kg/m³ depending on altitude and temperature"
      },
      "applications": [
        "Mission planning: calculate achievable range and flight time under forecast wind conditions",
        "Determine maximum safe operating wind speed for bridge inspection drones",
        "Aerodynamic fairing design to minimize CdA for long-range delivery drones",
        "Wind tunnel or CFD testing of drone frame drag characteristics"
      ],
      "relatedSkills": ["skill_002", "skill_001", "skill_017"],
      "complexity": 7,
      "source": "Wind Effects on Structures (Simiu & Scanlan), DJI Matrice 300 RTK Wind Resistance Specs"
    },
    {
      "id": "skill_019",
      "title": "PID Control Loop Tuning",
      "category": "Control_Systems",
      "description": "PID (Proportional-Integral-Derivative) controllers are the core stabilization algorithm in drone flight controllers. They continuously calculate error between desired and actual state (angle, rate, position) and output corrective motor commands. Proper PID tuning determines flight feel, stability, and disturbance rejection quality.",
      "keyPoints": [
        "P (Proportional): Output proportional to current error — primary correction force",
        "I (Integral): Accumulates past error — eliminates steady-state offset (e.g., CG drift)",
        "D (Derivative): Reacts to rate of error change — provides damping, prevents overshoot",
        "Cascaded PID: outer loop (angle) feeds setpoint to inner loop (rate) for better performance",
        "Typical tuning order: Rate P → Rate D → Rate I → Angle P, using step response analysis"
      ],
      "formulas": [
        "PID output: u(t) = Kp × e(t) + Ki × ∫e(t)dt + Kd × de(t)/dt",
        "Discrete form: u[n] = Kp × e[n] + Ki × Σe[k]×Δt + Kd × (e[n]−e[n−1])/Δt",
        "Ziegler-Nichols: For quarter-decay, Kp = 0.6×Ku, Ki = 2×Kp/Tu, Kd = Kp×Tu/8",
        "Where: Ku = ultimate gain (oscillation onset), Tu = oscillation period",
        "Loop bandwidth: f_BW ≈ Kp / (2π × I_frame) for rate loop"
      ],
      "specifications": {
        "rate_loop_frequency": "2–8 kHz (Betaflight/ArduPilot)",
        "angle_loop_frequency": "500–1000 Hz",
        "position_loop_frequency": "50–200 Hz",
        "typical_rate_P_5inch": "30–60 (Betaflight units)",
        "typical_rate_D_5inch": "20–40 (Betaflight units)",
        "typical_rate_I_5inch": "60–120 (Betaflight units)",
        "D_term_lowpass_filter": "100–150 Hz (to suppress noise amplification)"
      },
      "applications": [
        "Tune a 5\" freestyle quad for responsive, locked-in feel without oscillations",
        "Autonomous GPS waypoint holding with position PID outer loop (±0.5m accuracy)",
        "Altitude hold tuning using barometer/accelerometer feedback with anti-windup",
        "Adaptive PID gain scheduling for variable payload weight drones"
      ],
      "relatedSkills": ["skill_015", "skill_020", "skill_003"],
      "complexity": 9,
      "source": "Modern Control Engineering (Ogata, 5th Ed.), Betaflight Wiki, ArduPilot Tuning Guide"
    },
    {
      "id": "skill_020",
      "title": "IMU Calibration & Sensor Fusion",
      "category": "Control_Systems",
      "description": "IMU calibration corrects for manufacturing biases, scale factor errors, and cross-axis sensitivity in MEMS gyroscopes and accelerometers. Sensor fusion algorithms (Extended Kalman Filter, Mahony/Madgwick filters) combine IMU data with magnetometer and GPS to produce drift-free attitude and position estimates.",
      "keyPoints": [
        "Gyroscope bias drift: 1–10 °/hour for MEMS — must be calibrated at startup",
        "Accelerometer offset calibration: 6-position static calibration (each axis ±g)",
        "Magnetometer requires hard-iron and soft-iron calibration to correct for onboard interference",
        "EKF (Extended Kalman Filter) is the gold standard — used in ArduPilot and PX4",
        "Allan variance analysis characterizes long-term sensor noise and bias stability"
      ],
      "formulas": [
        "Bias correction: ω_corrected = ω_raw − ω_bias",
        "Scale factor: a_corrected = S × (a_raw − b), where S = scale matrix, b = bias vector",
        "EKF prediction: x̂(k|k−1) = F × x̂(k−1) + B × u(k)",
        "EKF update: x̂(k) = x̂(k|k−1) + K × (z(k) − H × x̂(k|k−1))",
        "Kalman gain: K = P(k|k−1) × Hᵀ × (H × P(k|k−1) × Hᵀ + R)⁻¹",
        "Attitude quaternion update: q(t+dt) = q(t) ⊗ Δq(ω, dt)"
      ],
      "specifications": {
        "gyro_bias_stability_MEMS": "1–10 °/hour",
        "accel_bias_stability_MEMS": "0.01–0.1 mg",
        "magnetometer_hard_iron_typical": "±200 μT onboard interference",
        "EKF_state_vector_size": "24 states (ArduPilot EKF3)",
        "calibration_temperature_range": "−10°C to +50°C for full compensation",
        "heading_accuracy_after_cal": "±1–3° (magnetometer fused)",
        "attitude_accuracy_after_fusion": "±0.1–0.5° (EKF with GPS)"
      },
      "applications": [
        "Pre-flight IMU calibration routine ensuring gyro bias < 0.5°/s before arming",
        "Magnetometer calibration dance (rotation on all axes) for accurate compass heading",
        "EKF health monitoring — automatic fallback to secondary IMU on anomaly detection",
        "Temperature-compensated IMU calibration tables for wide-operating-range industrial drones"
      ],
      "relatedSkills": ["skill_015", "skill_019", "skill_017"],
      "complexity": 9,
      "source": "Probabilistic Robotics (Thrun), ArduPilot EKF3 Source Documentation, IEEE Sensors Journal"
    }
  ]
};

export const categoryColors: Record<string, { bg: string; text: string; border: string; gradient: string; icon: string }> = {
  Physics: {
    bg: "bg-blue-50",
    text: "text-blue-700",
    border: "border-blue-200",
    gradient: "from-blue-500 to-blue-700",
    icon: "⚛️"
  },
  Materials: {
    bg: "bg-emerald-50",
    text: "text-emerald-700",
    border: "border-emerald-200",
    gradient: "from-emerald-500 to-emerald-700",
    icon: "🧬"
  },
  Mechanics: {
    bg: "bg-amber-50",
    text: "text-amber-700",
    border: "border-amber-200",
    gradient: "from-amber-500 to-amber-700",
    icon: "⚙️"
  },
  Circuits: {
    bg: "bg-purple-50",
    text: "text-purple-700",
    border: "border-purple-200",
    gradient: "from-purple-500 to-purple-700",
    icon: "⚡"
  },
  Aerodynamics: {
    bg: "bg-cyan-50",
    text: "text-cyan-700",
    border: "border-cyan-200",
    gradient: "from-cyan-500 to-cyan-700",
    icon: "💨"
  },
  Control_Systems: {
    bg: "bg-rose-50",
    text: "text-rose-700",
    border: "border-rose-200",
    gradient: "from-rose-500 to-rose-700",
    icon: "🎛️"
  }
};

export const categoryDescriptions: Record<string, string> = {
  Physics: "Fundamental forces & energy principles governing drone flight",
  Materials: "Engineering materials, properties, and selection criteria",
  Mechanics: "Structural design, rotors, motors, and mechanical systems",
  Circuits: "Electronics, power systems, and sensor technology",
  Aerodynamics: "Airflow analysis, propeller efficiency, and stability",
  Control_Systems: "Flight control algorithms, PID tuning, and sensor fusion"
};
